version: "3.6"

networks:
    ambient:
      external: true

services:
  ambient:
    build: .
    image: cmclean165/ambient-cloud:latest
    restart: unless-stopped
    networks:
      - ambient
    environment:
      - DEPLOYED_URL=flow-ambient.ngrok.app
    volumes:
      - ./db_version:/root/.flowise
    working_dir: /usr/src/packages
    command: [ "yarn", "start" ]

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    networks:
      - ambient
    command:
      - start
      - --all
      - --config=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

  