version: "3.6"

networks:
  ambient:

services:
  ambient:
    image: cmclean165/ambient-cloud:latest
    restart: unless-stopped
    networks:
      - ambient
    environment:
      - DEPLOYED_URL=www.ambientware.co
      - BASE_URL=https://www.ambientware.co
      - OPENAI_API_KEY={OPENAI_API_KEY}
    volumes:
      - ./db_version:/root/.flowise
    working_dir: /usr/src/packages
    command: ["yarn", "start"]
    ports:
      - 3000:3000
