version: "3.6"

networks:
  ambient:

services:
  ambient:
    build: .
    image: cmclean165/ambient-cloud:latest
    restart: unless-stopped
    networks:
      - ambient
    env_file:
      - packages/server/.env
    working_dir: /usr/src/packages
    command: ["yarn", "start"]
    ports:
      - 3000:3000
