const blacklistNodes = [
    'awsBedrock',
    'azureOpenAI',
    'chromaExistingIndex',
    'chromaUpsert',
    'cohere',
    'faissExistingIndex',
    'faissUpsert',
    'GooglePaLM',
    'googlevertexai',
    'huggingFaceInference_LLMs',
    'memoryVectorStore',
    'NIBittensorLLM',
    'openAI',
    'openSearchExistingIndex',
    'openSearchUpsertDocument',
    'pineconeExistingIndex',
    'pineconeUpsert',
    'postgresExistingIndex',
    'postgresUpsert',
    'qdrantExistingIndex',
    'qdrantUpsert',
    'replicate',
    'singlestoreExisting',
    'singlestoreUpsert',
    'supabaseExistingIndex',
    'supabaseUpsert',
    'vectaraExistingIndex',
    'vectaraUpload',
    'vectaraUpsert',
    'weaviateExistingIndex',
    'weaviateUpsert',
    'zepExistingIndex',
    'zepUpsert',
]

export default blacklistNodes;