const whitelistNodes = [
    'agentTool',
    'aiPlugin',
    'airtable',
    'airtableAgent',
    'apifyWebsiteContentCrawler',
    'apiLoader',
    // 'autoGPT',
    'awsBedrock',
    'AWSBedrockEmbeddings',
    'awsChatBedrock',
    'azureChatOpenAI',
    'azureOpenAI',
    'azureOpenAIEmbeddings',
    // 'babyAGI',
    'braveSearchAPI',
    'bufferMemory',
    'bufferWindowMemory',
    'calculator',
    'chainTool',
    'characterTextSplitter',
    'chatAnthropic',
    'chatGooglePaLM',
    'chatGoogleVertexAI',
    'chatHuggingFace',
    'chatLocalAI',
    // 'chatOllama',
    'chatOpenAI',
    'chatOpenAICustom',
    'chatPromptTemplate',
    'cheerioWebScraper',
    // 'chromaExistingIndex',
    // 'chromaUpsert',
    'cloudCollection',
    'cloudCollectionUpsert',
    'codeTextSplitter',
    'cohere',
    'cohereEmbeddings',
    'confluence',
    'conversationalAgent',
    'conversationalRetrievalAgent',
    'conversationalRetrievalQAChain',
    'conversationChain',
    'conversationSummaryMemory',
    'csvAgent',
    'csvFile',
    'csvOutputParser',
    'customAutomation',
    'customListOutputParser',
    'customTool',
    'docxFile',
    // 'DynamoDBChatMemory',
    'edgarFilingLoader',
    // 'ElasticsearchIndex',
    // 'ElasticsearchUpsert',
    // 'faissExistingIndex',
    // 'faissUpsert',
    'fewShotPromptTemplate',
    'figma',
    'folderFiles',
    'getApiChain',
    'gitbook',
    'github',
    'gmailAutomation',
    'gmailHandler',
    'googleCustomSearch',
    'GooglePaLM',
    'googlePaLMEmbeddings',
    'googlevertexai',
    'googlevertexaiEmbeddings',
    'htmlToMarkdownTextSplitter',
    'huggingFaceInference_LLMs',
    'huggingFaceInferenceEmbeddings',
    'HydeRetriever',
    // 'inMemoryCache',
    // 'inMemoryEmbeddingCache',
    'jsonFile',
    'jsonlinesFile',
    'langFuse',
    'langSmith',
    'llmChain',
    'llmonitor',
    'localAIEmbeddings',
    'localCollection',
    'localCollectionUpsert',
    'markdownTextSplitter',
    // 'memoryVectorStore',
    // 'milvusExistingCollection',
    // 'milvusUpsert',
    'momentoCache',
    'motorheadMemory',
    'mrklAgentChat',
    'mrklAgentLLM',
    'multiPromptChain',
    'multiRetrievalQAChain',
    // 'NIBittensorChatModel',
    // 'NIBittensorLLM',
    'notionDB',
    'notionFolder',
    'notionPage',
    // 'ollama',
    // 'ollamaEmbedding',
    'openAI',
    'openAIAssistant',
    'openaiCollection',
    'openAIEmbeddings',
    'openAIEmbeddingsCustom',
    'openAIFunctionAgent',
    'openApiChain',
    'openAPIToolkit',
    // 'openSearchExistingIndex',
    // 'openSearchUpsertDocument',
    'pdfFile',
    // 'pineconeExistingIndex',
    // 'pineconeUpsert',
    'plainText',
    'planAndExecuteAgent',
    'playwrightWebScraper',
    'postApiChain',
    // 'postgresExistingIndex',
    // 'postgresUpsert',
    'postRequestAutomation',
    'postRequestHandler',
    'promptRetriever',
    'promptTemplate',
    'puppeteerWebScraper',
    // 'qdrantExistingIndex',
    // 'qdrantUpsert',
    'readFile',
    'recursiveCharacterTextSplitter',
    'RedisBackedChatMemory',
    'redisCache',
    'redisEmbeddingsCache',
    // 'RedisIndex',
    // 'RedisUpsert',
    'replicate',
    'requestsGet',
    'requestsPost',
    'retrievalQAChain',
    'retrieverTool',
    'S3',
    'scheduleAutomation',
    'searchApi',
    'searchAPI',
    'serpApi',
    'serpAPI',
    'serper',
    'similarityThresholdRetriever',
    // 'singlestoreExisting',
    // 'singlestoreUpsert',
    'slackCommandAutomation',
    'slackEventAutomation',
    'sqlDatabaseChain',
    'structuredOutputParser',
    'subtitlesFile',
    // 'supabaseExistingIndex',
    // 'supabaseUpsert',
    'textFile',
    'tokenTextSplitter',
    'unstructuredFileLoader',
    'unstructuredFolderLoader',
    'upstashRedisBackedChatMemory',
    'upstashRedisCache',
    // 'vectaraExistingIndex',
    // 'vectaraUpload',
    // 'vectaraUpsert',
    'vectorDBQAChain',
    'vectorStoreRetriever',
    'vectorStoreToDocument',
    // 'weaviateExistingIndex',
    // 'weaviateUpsert',
    'webBrowser',
    'writeFile',
    'zapierAutomation',
    'zapierNLA',
    // 'zepExistingIndex',
    'ZepMemory',
    // 'zepUpsert',
]

export default whitelistNodes
