const whitelistNodes = [
    'agentTool',
    'aiPlugin',
    // 'airtable',
    'airtableAgent',
    // 'apifyWebsiteContentCrawler',
    // 'apiLoader',
    // 'autoGPT',
    'awsBedrock',
    // 'AWSBedrockEmbeddings',
    'awsChatBedrock',
    'azureChatOpenAI',
    'azureOpenAI',
    // 'azureOpenAIEmbeddings',
    // 'babyAGI',
    'braveSearchAPI',
    // 'bufferMemory',
    // 'bufferWindowMemory',
    'calculator',
    'chainTool',
    // 'characterTextSplitter',
    'chatAnthropic',
    'chatGooglePaLM',
    'chatGoogleVertexAI',
    'chatHuggingFace',
    'chatLocalAI',
    // 'chatOllama',
    'chatOpenAI',
    'chatOpenAICustom',
    'chatPromptTemplate',
    // 'cheerioWebScraper',
    // 'chroma',
    // 'chromaExistingIndex',
    // 'chromaUpsert',
    'cloudCollection',
    // 'cloudCollectionUpsert',
    // 'codeTextSplitter',
    'cohere',
    // 'cohereEmbeddings',
    // 'confluence',
    'conversationalAgent',
    'conversationalRetrievalAgent',
    'conversationalRetrievalQAChain',
    'conversationChain',
    // 'conversationSummaryMemory',
    'csvAgent',
    // 'csvFile',
    'csvOutputParser',
    // 'customAutomation',
    'customListOutputParser',
    'customTool',
    // 'docxFile',
    // 'DynamoDBChatMemory',
    // 'edgarFilingLoader',
    // 'elasticsearch',
    // 'ElasticsearchIndex',
    // 'ElasticsearchUpsert',
    // 'faiss',
    // 'faissExistingIndex',
    // 'faissUpsert',
    'fewShotPromptTemplate',
    // 'figma',
    // 'folderFiles',
    'getApiChain',
    // 'gitbook',
    // 'github',
    'gmailAutomation',
    'gmailHandler',
    'googleCustomSearch',
    'GooglePaLM',
    // 'googlePaLMEmbeddings',
    'googlevertexai',
    // 'googlevertexaiEmbeddings',
    // 'htmlToMarkdownTextSplitter',
    'huggingFaceInference_LLMs',
    // 'huggingFaceInferenceEmbeddings',
    // 'HydeRetriever',
    // 'inMemoryCache',
    // 'inMemoryEmbeddingCache',
    'inputModerationOpenAI',
    'inputModerationSimple',
    // 'jsonFile',
    // 'jsonlinesFile',
    'langFuse',
    'langSmith',
    'llmChain',
    'llmonitor',
    // 'localAIEmbeddings',
    'localCollection',
    // 'localCollectionUpsert',
    // 'markdownTextSplitter',
    // 'memoryVectorStore',
    // 'milvus',
    // 'milvusExistingCollection',
    // 'milvusUpsert',
    // 'momentoCache',
    // 'mongoDBAtlas',
    // 'MongoDBAtlasChatMemory',
    // 'MongoDBIndex',
    // 'MongoDBUpsert',
    // 'motorheadMemory',
    'mrklAgentChat',
    'mrklAgentLLM',
    'multiPromptChain',
    'multiRetrievalQAChain',
    // 'NIBittensorChatModel',
    // 'NIBittensorLLM',
    'noteAnnotation',
    // 'notionDB',
    // 'notionFolder',
    // 'notionPage',
    // 'ollama',
    // 'ollamaEmbedding',
    'openAI',
    'openAIAssistant',
    // 'openaiCollection',
    // 'openAIEmbeddings',
    // 'openAIEmbeddingsCustom',
    'openAIFunctionAgent',
    'openApiChain',
    'openAPIToolkit',
    // 'openSearch',
    // 'openSearchExistingIndex',
    // 'openSearchUpsertDocument',
    // 'pdfFile',
    // 'pinecone',
    // 'pineconeExistingIndex',
    // 'pineconeUpsert',
    // 'plainText',
    'planAndExecuteAgent',
    // 'playwrightWebScraper',
    'postApiChain',
    // 'postgres',
    // 'postgresExistingIndex',
    // 'postgresUpsert',
    'postRequestAutomation',
    'postRequestHandler',
    // 'promptRetriever',
    'promptTemplate',
    // 'puppeteerWebScraper',
    // 'qdrant',
    // 'qdrantExistingIndex',
    // 'qdrantUpsert',
    'readFile',
    // 'recursiveCharacterTextSplitter',
    // 'redis',
    // 'RedisBackedChatMemory',
    // 'redisCache',
    // 'redisEmbeddingsCache',
    // 'RedisIndex',
    // 'RedisUpsert',
    'replicate',
    'requestsGet',
    'requestsPost',
    'retrievalQAChain',
    'retrieverTool',
    // 'S3',
    'scheduleAutomation',
    // 'searchApi',
    'searchAPI',
    // 'serpApi',
    'serpAPI',
    'serper',
    // 'similarityThresholdRetriever',
    // 'singlestore',
    // 'singlestoreExisting',
    // 'singlestoreUpsert',
    'slackCommandAutomation',
    'slackEventAutomation',
    'sqlDatabaseChain',
    'structuredOutputParser',
    // 'subtitlesFile',
    // 'supabase',
    // 'supabaseExistingIndex',
    // 'supabaseUpsert',
    // 'textFile',
    // 'tokenTextSplitter',
    // 'unstructuredFileLoader',
    // 'unstructuredFolderLoader',
    // 'upstashRedisBackedChatMemory',
    // 'upstashRedisCache',
    // 'vectara',
    // 'vectaraExistingIndex',
    // 'vectaraQAChain',
    // 'vectaraUpload',
    // 'vectaraUpsert',
    'vectorDBQAChain',
    // 'vectorStoreRetriever',
    // 'vectorStoreToDocument',
    // 'weaviate',
    // 'weaviateExistingIndex',
    // 'weaviateUpsert',
    'webBrowser',
    'writeFile',
    'zapierAutomation',
    'zapierNLA'
    // 'zep',
    // 'zepExistingIndex',
    // 'ZepMemory',
    // 'zepUpsert',
]

export default whitelistNodes
